[package]
name = "fuse_mbox"
version = "0.1.0"
authors = ["Damian J Pound <damian@thebestisp.com>"]
edition = "2018"

[dependencies]
fuse    = "0.3.1"
hex     = "0.4.2"
libc    = "0.2"
mailbox = "0.2.0"
memmap  = "0.7.0"
time    = "0.1"
